### PR TITLE
Allow index file to not exist

### PR DESCRIPTION
**Pull request by runemadsen**
This change fixes a few things:
- If you don't have an index file, it will simply use the existing `/pages/1/index.html` file contents. This allows you to just rename the first page to something like `/blog/index.html`.
- This makes the pagination point to the correct page when moving from page 2 to a renamed page 1. This was broken.

### CODE REVIEW

**Comment by brunoscopelliti** [comment]
Hi @runemadsen ,

Thank you for your interest in metalsmith-pager.

Currently I'm not actively using metalsmith in any project of mine, so it's quite a bit of time I don't look at this code... 

If I remember correctly, currently your best bet to make the `index` page have the same content of the page `/pages/1/index.html` is to set explicitly `index` equal to `/pages/1/index.html`.
Is this that you want to obtain?

I'm also having hard times understand what you mean here:

>This allows you to just rename the first page to something like /blog/index.html.

Do you mean manually moving `/pages/1/index.html` to `/blog/index.html`?

**Comment by runemadsen** [comment]
Thanks.

To explain a little more: This pull request allows you to have a website with a bunch of categories (`/blog`, `/projects`, etc), and have the first page of each of the categories end up on `/blog/index.html` and `/projects/index.html` without copy/pasting the template to those files. You can just set the `index` parameter, and the file will end up there instead. 

It also fixes a bug when the `index` parameter is used, so the `prev` link points to the right file. It shouldn't break any existing functionality, so would you consider merging it and publishing a new version?

**Comment by brunoscopelliti** [comment]
Ok, it seems a common use case to me.

Before testing your code by myself, I would ask you a last thing... Would you mind to update your commit to reflect the style in place 8(that is curly brace even on one-liner if, and always semicolon)?

Thank you

**Comment by runemadsen** [comment]
Done!

**Comment by brunoscopelliti** [comment]
Would you mind fixing the tests?
I've run `npm test` just now, and noticed that the last test is broken by this changeset.

Also feel free to add a test for the bug you've mentioned before.

> This makes the pagination point to the correct page when moving from page 2 to a renamed page 1. This was broken.

Appreciate your help!

**Comment by runemadsen** [comment]
What test is broken for you? All my tests are passing. Ignore the comment about pagination. I was submitting PR's for a few NPM modules and mixed it up.

**Comment by runemadsen** [comment]
Sorry about that. Should be fixed now. I also took the time to clean up the logic a bit. At some point, the tests should probably be rewritten to take advantage of the metalsmith file loading instead of stubs, but I think it's all looking good for now.

**Comment by brunoscopelliti** [comment]
Ok, I don't see regressions.
However when I do not set the `index` option, pagination is OK, and starts from `page/1/index.html`, but an `index.html` page is still created, but almost empty. 
I don't think this is the intended behaviour.

**Comment by runemadsen** [comment]
Hmmm, I don't see that behavior. I added [a test for this problem](https://github.com/runemadsen/metalsmith-pager/blob/9f31849ab5960aa1fd40819e45c68f80ba183b53/tests/metalsmith-pager.js#L154-L186). If you can make that test fail, I'll be happy to tweak.

I also cleaned up the tests a bit to make it harder to make a mistake when stubbing the files and metalsmith metadata.

**Comment by brunoscopelliti** [comment]
Ok, I've verified that the index.html is not added by metalsmith-pager; also the test you've written helps a lot!
Thanks for your help.

**Comment by brunoscopelliti** [comment]
Going to publish the new package on npm too.

**Pull request merged**
